import type { BlogPost } from "@/backend.d";

export const SEED_BLOG_POSTS: BlogPost[] = [
  {
    id: "seed_1",
    slug: "what-is-mat-and-why-it-works",
    title:
      "What Is Medication-Assisted Treatment — and Why the Science Says It Works",
    author: "Dom, Founder",
    publishedAt: BigInt("1700000000000000000"),
    isPublished: true,
    excerpt:
      "MAT combines FDA-approved medications with counseling and behavioral therapies to treat substance use disorders. The evidence is overwhelming — and yet stigma persists. Here's what the science actually shows.",
    content:
      "Medication-Assisted Treatment (MAT) is the use of FDA-approved medications — such as buprenorphine (Suboxone), methadone, and naltrexone (Vivitrol) — combined with counseling and behavioral therapies to treat opioid use disorder (OUD).\n\nDespite decades of clinical evidence supporting its effectiveness, MAT remains one of the most misunderstood and stigmatized forms of medical treatment in the United States. The goal of this post is to cut through the noise.\n\n**What the Research Shows**\n\nThe Substance Abuse and Mental Health Services Administration (SAMHSA) and the National Institute on Drug Abuse (NIDA) both confirm that MAT reduces illicit opioid use and criminal activity, improves social functioning and retention in treatment, decreases risk of overdose death by up to 50%, and is more effective than abstinence-only approaches for moderate to severe OUD.\n\nA 2019 study published in the New England Journal of Medicine found that extended-release naltrexone and buprenorphine-naloxone were equally effective at preventing relapse — both significantly better than no medication at all.\n\n**The Medications**\n\nBuprenorphine (brand names: Suboxone, Sublocade) is a partial opioid agonist. It reduces cravings and withdrawal symptoms without producing the euphoric high of full opioids. It can be prescribed in an office-based setting, which dramatically increases access.\n\nMethadone is a full opioid agonist dispensed through federally regulated clinics. It has a long track record of effectiveness but requires daily clinic visits, which creates access barriers for many patients.\n\nNaltrexone (Vivitrol) blocks opioid receptors entirely, preventing any opioid from producing its effects. It is non-addictive and ideal for patients who have already completed detox.\n\n**The Stigma Problem**\n\nOne of the most harmful misconceptions is that MAT is trading one addiction for another. This framing is medically incorrect. Addiction is characterized by compulsive use despite negative consequences. MAT patients taking medication as prescribed are undergoing medical treatment — no different from a diabetic taking insulin.\n\nStigma kills. When people are shamed out of treatment, they return to street opioids with unknown purity and lethal fentanyl contamination. The data on this is unambiguous.\n\n**The Bottom Line**\n\nIf you or someone you love is struggling with opioid use disorder, MAT is a medically validated, potentially life-saving option. The goal is not just abstinence — it is a functional, connected, meaningful life. MAT makes that possible for millions of people.\n\nLive Now Recovery exists to connect people to verified MAT providers in real time. Because the gap between needing help and finding it costs lives.",
  },
  {
    id: "seed_2",
    slug: "cost-plus-drugs-recovery-access",
    title:
      "Cost Plus Drugs: How One Pharmacy Model Is Changing Recovery Access",
    author: "Live Now Recovery Team",
    publishedAt: BigInt("1701000000000000000"),
    isPublished: true,
    excerpt:
      "Generic Naloxone for $61.36. Generic Naltrexone for $22.94. The cost-plus pharmacy model is dismantling one of the biggest barriers to recovery: price.",
    content:
      "For decades, the price of life-saving recovery medications has been one of the most insidious barriers to treatment. Naloxone — the overdose-reversal medication — could cost $150 or more at a traditional pharmacy. Naltrexone (ReVia), used to prevent relapse, routinely ran over $100 per month.\n\nEnter the cost-plus pharmacy model.\n\n**What Is Cost-Plus Pricing?**\n\nA cost-plus pharmacy charges the actual cost of the drug plus a small fixed markup and dispensing fee — rather than the opaque, insurance-negotiated pricing that dominates traditional pharmacies.\n\nThe result is transparent, dramatically lower prices for generic medications: Naloxone (Generic Narcan) at $61.36 vs. $143 retail average, saving $81.64. Naltrexone 50mg (Generic ReVia) at $22.94 vs. $102 retail average, saving $79.06.\n\n**Why This Matters for Recovery**\n\nCost is a documented barrier to both MAT initiation and retention. Patients who cannot afford their medications discontinue treatment — and discontinuation dramatically increases overdose risk.\n\nA 2021 study in Health Affairs found that medication cost was cited as a reason for treatment non-adherence in over 30% of MAT patients surveyed.\n\nBy making generic naltrexone available for under $25 per month, cost-plus pricing removes what may be the single most concrete financial obstacle to sustained recovery.\n\n**The Transparency Mandate**\n\nLive Now Recovery includes a pricing transparency card on every provider listing. Our commitment: every person searching for help should immediately see what their medication costs using the most affordable legal option available.\n\nYou should not have to choose between rent and recovery. Affordable MAT exists. We are here to help you find it.",
  },
  {
    id: "seed_3",
    slug: "ohio-opioid-crisis-data",
    title: "Ohio's Opioid Crisis by the Numbers: What the Data Actually Shows",
    author: "Live Now Recovery Team",
    publishedAt: BigInt("1702000000000000000"),
    isPublished: true,
    excerpt:
      "Ohio has one of the highest opioid overdose death rates in the nation. Behind every statistic is a person, a family, a community. Here is what the data shows — and what it demands.",
    content:
      "Ohio has been among the hardest-hit states in the opioid epidemic for over a decade. Understanding the scope of the crisis is not about shock value — it is about making the case for urgency, for resources, and for the kind of real-time infrastructure that Live Now Recovery is building.\n\n**The Numbers**\n\nAccording to the Ohio Department of Health and CDC data, Ohio consistently ranks in the top 5 states for opioid overdose death rates per 100,000 residents. In 2022, Ohio recorded approximately 4,600 overdose deaths — more than 12 per day. Fentanyl and fentanyl analogs were present in over 80% of those deaths. Cuyahoga County (Cleveland metro area) has historically had one of the highest overdose death rates of any county in the nation. Region 13 (Northeast Ohio) — the area Live Now Recovery serves — has been a persistent high-burden zone.\n\n**Who Is Affected**\n\nThe demographics of Ohio's opioid crisis have shifted significantly since the early prescription opioid wave of the 2000s. Today the crisis cuts across race, income level, and geography — rural, suburban, and urban communities are all affected. Young adults (25–34) represent the largest age group for overdose deaths. Veterans and people experiencing homelessness face disproportionately high risk. Co-occurring mental health conditions (depression, PTSD, anxiety) are present in the majority of patients with OUD.\n\n**Treatment Gaps**\n\nDespite the scale of the crisis, treatment access remains deeply inadequate. Only approximately 20% of people with OUD receive any form of specialty treatment in a given year (SAMHSA). Provider shortages, insurance barriers, stigma, and lack of real-time availability data all contribute to treatment gaps. In many Ohio ZIP codes, there is no verified MAT provider within a reasonable travel distance — or the nearest provider has no open slots.\n\n**The Case for Live Now**\n\nLive Now Recovery exists because the gap between needing help and finding it is not a technology problem — it is a will problem. The data exists. The providers exist. The medications exist. What has been missing is a real-time, privacy-first, mobile-optimized bridge.\n\nEvery ZIP code on our map is a community. Every pulse on our Impact Shadow visualization represents a real person searching for a way out. We are building the infrastructure that the data demands.",
  },
  {
    id: "seed_4",
    slug: "community-helpers-close-the-gap",
    title: "How Community Helpers Close the Gap When Clinics Can't",
    author: "Dom, Founder",
    publishedAt: BigInt("1703000000000000000"),
    isPublished: true,
    excerpt:
      "Clinics have hours. Addiction does not. Community Helpers are the peer bridge that operates in the gap — anonymous, decentralized, and real.",
    content:
      "There is a moment — and anyone who has been through it knows exactly what it feels like — when you know you need help, and the clinic is closed.\n\nIt might be 7 PM on a Friday. It might be a Sunday morning. It might be 2 AM on a Tuesday when the decision has been made and the window is narrow. Clinics have operating hours. Crisis does not respect operating hours.\n\nThis is why the Community Helper module exists.\n\n**What Is a Community Helper?**\n\nA Community Helper is a verified, anonymous peer who claims a ZIP code on the Live Now platform, signaling that they are available and willing to help connect someone to resources. No credentials required. No real name stored. Just a hash of an Internet Identity, a ZIP code, and a timestamp.\n\nHelpers can be anyone: someone in long-term recovery, a family member who has been through the process, a peer support specialist, a harm reduction volunteer. The only requirement is willingness.\n\n**The Proof of Presence System**\n\nWhen a Helper generates a QR code handoff token, they are creating a cryptographically verifiable record of peer presence. When that token is scanned and completed, it records — anonymously — that a real human bridge occurred. That connection happened. That moment was documented without storing a single piece of identifying information about either party.\n\nThis is what we call a Proof of Presence handoff. It is the core metric of Live Now Recovery because it measures what actually matters: not clicks, not signups — real human moments of connection.\n\n**Why Decentralization Matters**\n\nA centralized peer support model requires staff, scheduling, and funding. It can be defunded, under-resourced, or overwhelmed. A decentralized network of willing helpers, operating from their own phones in their own ZIP codes, is resilient by design.\n\nWhen search intents in a ZIP code spike — when the Sentinel Agent detects high demand and low coverage — the platform flags it as a high-risk area and calls for helpers to activate. The network responds to real-time community need.\n\n**A Personal Note**\n\nI did not have a community helper when I needed one. I had a phone book, a lot of fear, and not enough information. Every person who signs up as a helper is filling the gap that I fell into.\n\nIf you are in recovery and you are reading this: you already know something that is genuinely life-saving. Your experience is not a liability. It is a credential. Consider becoming a helper.\n\n— Dom",
  },
  {
    id: "seed_5",
    slug: "ten-years-in-the-program",
    title: "10 Years in the Program: Why I Built Live Now Recovery",
    author: "Dom, Founder",
    publishedAt: BigInt("1704000000000000000"),
    isPublished: true,
    excerpt:
      "I am 46 years old, 10 years in medically assisted treatment, and I built this platform because I lived the gap it fills. This is that story.",
    content:
      "I want to tell you something I do not say often enough: I am proud of where I am.\n\nThat is not a small thing. For a long time, I was not sure I would make it to this point. Not sure there was a point. Medically assisted treatment gave me back the possibility of a future. Brightside Clinic — when it was one small location, before it grew into what it is now — was the first place that treated me like my life was worth saving.\n\nThat was close to a decade ago. I was not in a good place. I did not know what MAT was. I did not know what Suboxone was. I did not know that there was a scientifically validated, medically proven path out of where I was standing. I found out through a combination of luck, desperation, and a person who handed me a piece of paper with an address on it.\n\nOne piece of paper. That was the bridge.\n\n**The Gap**\n\nWhat I know now — after 10 years in the program, after watching others struggle to find what I found — is that the gap between needing help and finding it is not a small gap. It is not a minor inconvenience. It is the gap where people die.\n\nPeople die because they did not know there was an open clinic three miles away. People die because the clinic they called had a six-week wait and they could not hold on for six weeks. People die because they searched online and found outdated information, disconnected phone numbers, and no indication of whether anyone was actually available.\n\nThat gap is not inevitable. It is a solvable problem.\n\n**Why I Built This**\n\nI am not a software engineer. I am a person in recovery who learned enough to understand that the tools exist to close this gap — and that nobody was building them for the people who need them most.\n\nLive Now Recovery is the app I wish I had. Real-time provider availability. Anonymous search. No accounts required just to find out if a clinic is open. A community of helpers who are one tap away. Drug pricing transparency so that cost is never the reason someone walks away.\n\nThis is not a startup. This is not a product roadmap. This is a life raft, built by someone who needed one.\n\n**What I Believe**\n\nI believe that recovery is possible for anyone. I believe that access to treatment should not depend on what you know, who you know, or what you can afford. I believe that technology, used correctly, can be one of the most powerful tools for health equity that has ever existed.\n\nAnd I believe that the hardest part is the moment right before you ask for help — and that if we can make that moment even slightly less impossible, we can save lives.\n\nNo hurdle stops this. No wall stops this. People are out here who care, who are building, who have your back.\n\nYou are not alone.\n\n— Dom, Founder",
  },
];
