/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Provider {
  'id' : string,
  'zip' : string,
  'name' : string,
  'isLive' : boolean,
  'lastVerified' : bigint,
  'isVerified' : boolean,
  'address' : string,
  'phone' : string,
}
export interface ProviderInput {
  'zip' : string,
  'name' : string,
  'address' : string,
  'phone' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProvider' : ActorMethod<[ProviderInput], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getActiveProviders' : ActorMethod<[], Array<Provider>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProvider' : ActorMethod<[string], Provider>,
  'getProviderByPrincipal' : ActorMethod<[], [] | [Provider]>,
  'getProviders' : ActorMethod<[], Array<Provider>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleLiveStatus' : ActorMethod<[string], undefined>,
  'verifyProvider' : ActorMethod<[string, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];