/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProviderInput = IDL.Record({
  'zip' : IDL.Text,
  'name' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Provider = IDL.Record({
  'id' : IDL.Text,
  'zip' : IDL.Text,
  'name' : IDL.Text,
  'isLive' : IDL.Bool,
  'lastVerified' : IDL.Int,
  'isVerified' : IDL.Bool,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProvider' : IDL.Func([ProviderInput], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getActiveProviders' : IDL.Func([], [IDL.Vec(Provider)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProvider' : IDL.Func([IDL.Text], [Provider], ['query']),
  'getProviderByPrincipal' : IDL.Func([], [IDL.Opt(Provider)], ['query']),
  'getProviders' : IDL.Func([], [IDL.Vec(Provider)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleLiveStatus' : IDL.Func([IDL.Text], [], []),
  'verifyProvider' : IDL.Func([IDL.Text, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProviderInput = IDL.Record({
    'zip' : IDL.Text,
    'name' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Provider = IDL.Record({
    'id' : IDL.Text,
    'zip' : IDL.Text,
    'name' : IDL.Text,
    'isLive' : IDL.Bool,
    'lastVerified' : IDL.Int,
    'isVerified' : IDL.Bool,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProvider' : IDL.Func([ProviderInput], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getActiveProviders' : IDL.Func([], [IDL.Vec(Provider)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProvider' : IDL.Func([IDL.Text], [Provider], ['query']),
    'getProviderByPrincipal' : IDL.Func([], [IDL.Opt(Provider)], ['query']),
    'getProviders' : IDL.Func([], [IDL.Vec(Provider)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleLiveStatus' : IDL.Func([IDL.Text], [], []),
    'verifyProvider' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };